package main

import (
	_ "employee/routers"
	"github.com/beego/beego/v2/client/orm"
	_ "github.com/dbohachev/beego-swagger/example/beego-api/docs" // Docs, generated by the tool
	"log"

	beego "github.com/beego/beego/v2/server/web"
	_ "github.com/go-sql-driver/mysql"
)

func init() {
	sqlConn, err := beego.AppConfig.String("sqlconn")
	if err != nil {
		log.Println(err)
	}
	err = orm.RegisterDriver("mysql", orm.DRMySQL)
	if err != nil {
		log.Println(err.Error())
	}
	err = orm.RegisterDataBase("default", "mysql", sqlConn)
	if err != nil {
		log.Println(err.Error())
	}
	// Database alias.r
	name := "default"
	// Drop table and re-create.
	force := false
	// Print log.
	verbose := true
	// Error.
	err = orm.RunSyncdb(name, force, verbose)
	if err != nil {
		log.Println(err)
	}
}


func main() {

	if beego.BConfig.RunMode == "dev" {
		beego.BConfig.WebConfig.DirectoryIndex = true
		beego.BConfig.WebConfig.StaticDir["/swagger"] = "swagger"
	}
	beego.Run()
}
